In [8]:
import numpy as np

In [134]:
def update_field(field, exit, reward, gamma):
    shape = field.shape
    new_field = np.empty(shape)
    for i in range(i_ax):
        i_fractor = 0
        if i > 0:
            i_fractor += 1
        if i < shape[0] - 1:
            i_fractor += 1
        for j in range(j_ax):
            if i == exit[0] and j == exit[1]:
                continue
            j_fractor = 0
            if j > 0:
                j_fractor += 1
            if j < shape[1] - 1:
                j_fractor += 1
            fractor = i_fractor + j_fractor
            new_value = 0
            if i > 0:
                new_value += gamma * field[i - 1, j] + reward
            if i < shape[0] - 1:
                new_value += gamma * field[i + 1, j] + reward
            if j > 0:
                new_value += gamma * field[i, j - 1] + reward
            if j < shape[1] - 1:
                new_value += gamma * field[i, j + 1] + reward
            new_field[i, j] = new_value / fractor
    return new_field

In [130]:
i_ax, j_ax = 4, 5

In [131]:
exit = (np.random.choice(i_ax, 1)[0], np.random.choice(j_ax, 1)[0])
exit

(2, 2)

In [135]:
gamma = 0.9

In [132]:
field = np.zeros((i_ax, j_ax))

In [133]:
field

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [169]:
field = update_field(field, exit, -1, gamma)
print(np.around(field, 2))

[[-7.77 -7.58 -7.26 -7.58 -7.77]
 [-7.48 -6.91 -5.74 -6.91 -7.48]
 [-6.95 -5.49  0.   -5.49 -6.95]
 [-6.87 -6.1  -4.66 -6.1  -6.87]]


In [54]:
print(np.around(field, 2))

[[-14.06 -16.47 -18.87 -20.48 -21.14]
 [-10.37 -14.86 -18.3  -20.33 -21.12]
 [  0.   -11.89 -17.29 -19.91 -20.9 ]
 [ -7.18 -12.71 -17.04 -19.6  -20.6 ]]


In [55]:
field

array([[-14.05926433, -16.47144919, -18.86972537, -20.47689807,
        -21.14156761],
       [-10.37330076, -14.86232989, -18.29899878, -20.33457581,
        -21.11784912],
       [  0.        , -11.89401167, -17.29251505, -19.91353466,
        -20.89706529],
       [ -7.17967955, -12.70692893, -17.03711234, -19.59629316,
        -20.59814471]])

In [6]:
field = np.zeros((2, 3))
field

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
reward = np.zeros_like(field)
reward[0, 0] = -1
reward[1, 2] = -1
reward[0, 2] = -2
reward[1, 0] = -2
reward[0, 1] = -4
reward[1, 1] = -4
reward

array([[-1., -4., -2.],
       [-2., -4., -1.]])

In [13]:
def adjacent_cells(x, y, r, c):
    adj_cells = []
    for i, j in [(0, 1), (1, 0), (0, -1), (-1, 0)]:
        new_x, new_y = x + i, y + j
        if 0 <= new_x < r and 0 <= new_y < c:
            adj_cells.append((new_x, new_y))
    return adj_cells

In [ ]:
def update(field, reward, gamma):
    exit = (0, 2)
    r, c = field.shape
    new_field = np.zeros_like(field)
    for i in range(r):
        for j in range(c):
            neighbors = adjacent_cells(i, j, r, c)
            for n in neighbors:
                

In [ ]:
def get_state_value(state, start_values):
    ''' calculate the value of the specified state using the supplied current state values
      - this implements equation 9 '''

    # iterate over all possible actions for the state
    state_value = 0
    for action in get_π(state):
        
        target_state = action[0]
        action_probability = action[1]
        
        # iterate over all possible next states and rewards for the action   
        q_value = 0
        for action_dynamics in get_p( state, target_state ):
            next_state = action_dynamics['next_state']
            reward = action_dynamics['reward']
            probability = action_dynamics['probability']

            q_value += probability * (reward + start_values[next_state])

        state_value += action_probability * q_value
    
    return state_value   

# from baby robot

In [18]:
# the probability of moving from one state to the next
transition_probabilities = [
    [0.0, 0.5, 0.0, 0.5, 0.0, 0.0],     # Start
    [0.3, 0.0, 0.4, 0.0, 0.3, 0.0],     # S1
    [0.0, 0.2, 0.0, 0.0, 0.0, 0.8],     # S2
    [0.2, 0.0, 0.0, 0.0, 0.8, 0.0],     # S3
    [0.0, 0.3, 0.0, 0.3, 0.0, 0.4],     # S4
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]     # Exit

# the reward for moving to each of the states
state_rewards = [-1,-4,-2,-2,-4,-1]

# level details
level_width = 3
level_height = 2
splashes = [[0.0,1.0,0.5],
            [0.5,1.0,0.0]]

In [30]:
from enum import IntEnum
class State(IntEnum):
    Start, S1, S2, S3, S4, Exit = range(6)

class Puddle(IntEnum):
    Dry, Small, Large = range(3)  

In [31]:
start_values = np.zeros((State.Exit+1))
start_values

array([0., 0., 0., 0., 0., 0.])

In [32]:
def get_state_value(state ,start_values):
    ''' calculate the value of the specified state using the supplied current state values '''

    # iterate over all possible next states
    state_value = 0
    for next_state in State:
        # add the reward for moving to the next state and the value of the next state
        state_value += transition_probabilities[state][next_state] * (state_rewards[next_state] + start_values[next_state])        

    return state_value

In [34]:
get_state_value(State.Start, start_values)  

-3.0

In [ ]:
def get_target_states(s : State):
    ''' get the list of possible target states from the specified state '''    
    connections = connection_matrix[s]  
    # convert the list of connections into an array of state indexes      
    target_indexes = np.nonzero(connections)[0]   
    # convert the indexes to state enums
    return np.array([*State],object)[target_indexes]

In [ ]:
def get_policy(s : State):
    ''' given a state 's' return the possible actions and their probabilities - this is the policy 'π' '''        
    
    # get the set of possible target states
    target_states = get_target_states(s)

    # this policy makes all actions equally likely, so the probability of any action = 1/number of actions
    action_probability = 1 / target_states.shape[0]
    
    # create a structured array of targets and their probabilites
    actions = np.zeros(target_states.shape[0], dtype=[('target', State), ('probability', float)])
    actions['target'] = target_states
    actions['probability'] = action_probability   

    return actions

In [1]:
class Agent():
    def __init__(self):
        super().__init__()
        
        self.me_score = 0
        self.n_dice = 5
        self.roll = []
        self.tempo_score = 0
        self.n_turns = 0
    
    def refresh(self):
        self.me_score = 0
        self.n_dice = 5
        self.roll = []
        self.tempo_score = 0
        self.n_turns = 0

In [2]:
def make_roll(agent):
    agent.roll = np.random.randint(6, size = agent.n_dice)
    count = np.unique(agent.roll, return_counts = True)
    summ = 0
    for d, c in zip(count[0], count[1]):
        if d == 0:
            summ += 10 * c
        elif d == 4:
            summ += 5 * c
        else:
            continue
        agent.n_dice = agent.n_dice - c
        if agent.n_dice == 0:
            agent.n_dice = 5
            break
    if summ == 0:
        agent.tempo_score = 0
        return False
    else:
        agent.tempo_score = agent.tempo_score + summ
        return True

In [12]:
def turn(agent):
    while True:
        flag = make_roll(agent)
        print(agent.roll + 1, '\ntempo score:', agent.tempo_score, 'score:', agent.me_score, '\nturns:', agent.n_turns)
        if flag:
            score = agent.me_score + agent.tempo_score
            if score >= 1000:
                agent.me_score = score
                break
            action = input()
            if action == ' ':
                continue
            else:
                break
        else:
            break
    agent.me_score = agent.me_score + agent.tempo_score
    agent.tempo_score = 0
    agent.n_dice = 5
    agent.n_turns = agent.n_turns + 1

In [13]:
ag = Agent()
while True:
    turn(ag)
    if ag.me_score > 999:
        print(ag.me_score)
        break

[3 1 6 1 5] 
tempo score: 25 score: 0 
turns: 0


[3 6 1 3 6] 
tempo score: 10 score: 25 
turns: 1


[6 1 6 1] 
tempo score: 30 score: 25 
turns: 1


[2 6 2 6 1] 
tempo score: 10 score: 55 
turns: 2


[6 3 3 4] 
tempo score: 0 score: 55 
turns: 2
[1 5 2 6 6] 
tempo score: 15 score: 55 
turns: 3


[3 6 1] 
tempo score: 25 score: 55 
turns: 3


[5 4 3 4 4] 
tempo score: 5 score: 80 
turns: 4


[2 3 2 2] 
tempo score: 0 score: 80 
turns: 4
[3 1 5 1 1] 
tempo score: 35 score: 80 
turns: 5


[6 6 1 6 2] 
tempo score: 10 score: 115 
turns: 6


[4 2 2 6] 
tempo score: 0 score: 115 
turns: 6
[1 3 6 5 2] 
tempo score: 15 score: 115 
turns: 7


[6 6 3] 
tempo score: 0 score: 115 
turns: 7
[3 6 2 3 2] 
tempo score: 0 score: 115 
turns: 8
[1 2 3 3 5] 
tempo score: 15 score: 115 
turns: 9


[5 5 6] 
tempo score: 25 score: 115 
turns: 9


[5 5 3 1 3] 
tempo score: 20 score: 140 
turns: 10


[1 5 6 5 3] 
tempo score: 20 score: 160 
turns: 11


[5 1 6 1 4] 
tempo score: 25 score: 180 
turns: 12


[1 5 1 1 3] 
tempo score: 35 score: 205 
turns: 13


[5 3 2 6 2] 
tempo score: 5 score: 240 
turns: 14


[3 4 1 3] 
tempo score: 15 score: 240 
turns: 14


[6 3 4] 
tempo score: 0 score: 240 
turns: 14
[5 3 4 6 1] 
tempo score: 15 score: 240 
turns: 15


[5 2 5] 
tempo score: 25 score: 240 
turns: 15


[3 3 3 6 5] 
tempo score: 5 score: 265 
turns: 16


[5 2 6 2] 
tempo score: 10 score: 265 
turns: 16


[1 1 6] 
tempo score: 30 score: 265 
turns: 16


[5 4 5 5 6] 
tempo score: 15 score: 295 
turns: 17


[5 4 5 4 1] 
tempo score: 20 score: 310 
turns: 18


[3 2 6 1 1] 
tempo score: 20 score: 330 
turns: 19


[4 2 4] 
tempo score: 0 score: 330 
turns: 19
[6 1 2 5 1] 
tempo score: 25 score: 330 
turns: 20


[3 3 6 2 5] 
tempo score: 5 score: 355 
turns: 21


[2 3 5 4] 
tempo score: 10 score: 355 
turns: 21


[6 5 4] 
tempo score: 15 score: 355 
turns: 21


[6 1 3 3 1] 
tempo score: 20 score: 370 
turns: 22


[1 6 6] 
tempo score: 30 score: 370 
turns: 22


[2 4 1 3 1] 
tempo score: 20 score: 400 
turns: 23


KeyboardInterrupt: Interrupted by user